[package]
name = "mastobooper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
rand = "0.8.5"
rodio = { version = "0.15.0", default-features = false, features = [ "vorbis" ] }
